# Generated by Django 3.0.8 on 2020-09-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_supernote', models.CharField(max_length=30)),
                ('rebuttal_supernote', models.CharField(max_length=30)),
                ('rebuttal_chunk', models.IntegerField()),
                ('label', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=200)),
                ('annotator', models.CharField(max_length=30)),
                ('review_chunking_error', models.BooleanField(default=False)),
                ('rebuttal_chunking_error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatedPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_supernote', models.CharField(max_length=30)),
                ('rebuttal_supernote', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('reviewer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_supernote', models.CharField(max_length=30)),
                ('chunk_idx', models.IntegerField()),
                ('sentence_idx', models.IntegerField()),
                ('token_idx', models.IntegerField()),
                ('token', models.CharField(max_length=30)),
            ],
        ),
    ]
