# Generated by Django 3.0.8 on 2020-09-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0003_auto_20200918_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedpair',
            name='reviewer',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
